// Generated by CoffeeScript 1.3.3
(function() {
  var AccessibilityModePlain;

  AccessibilityModePlain = (function() {

    function AccessibilityModePlain() {}

    AccessibilityModePlain.prototype.gridSize = {
      columns: 3,
      rows: 3
    };

    AccessibilityModePlain.prototype.initializeDataSource = function(options, cb) {
      return this.makeDataSource(options, cb);
    };

    AccessibilityModePlain.prototype.makeDataSource = function(options, cb) {
      return new DataSource(options, cb);
    };

    return AccessibilityModePlain;

  })();

  window.AccessibilityModePlain = AccessibilityModePlain;

}).call(this);
