// Generated by CoffeeScript 1.3.3
(function() {
  var AccessibilityMode;

  AccessibilityMode = (function() {

    function AccessibilityMode() {}

    AccessibilityMode.prototype.initializeDataSource = function(options, cb) {
      var _this = this;
      return new DataSource({
        grid: options.grid,
        level: 1,
        nodeId: "yes_no",
        storage: options.storage
      }, function(err, yesNoDataSource) {
        _this.yesNoDataSource = yesNoDataSource;
        if (err != null) {
          return cb(err);
        }
        options.level = 1;
        return _this.makeDataSource(options, cb);
      });
    };

    AccessibilityMode.prototype.makeDataSource = function(options, cb) {
      var _this = this;
      return new DataSource(options, function(err, myDataSource) {
        var splitDataSource, _ref, _ref1;
        if (err != null) {
          return cb(err);
        }
        myDataSource.navTitle = ">";
        if ((((_ref = options.parent) != null ? _ref.navTitle : void 0) != null) && (((_ref1 = options.cellData) != null ? _ref1.label : void 0) != null)) {
          myDataSource.navTitle = options.parent.navTitle + " / " + options.cellData.label;
        }
        $('#navBar').html(myDataSource.navTitle);
        splitDataSource = new SplitDataSource(_this.yesNoDataSource, myDataSource, 1);
        return cb(null, splitDataSource);
      });
    };

    return AccessibilityMode;

  })();

  window.AccessibilityMode = AccessibilityMode;

}).call(this);
