// Generated by CoffeeScript 1.3.3
(function() {
  var root, _BlindKeyboardInput,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.KeyboardInput = (function() {
    var _instance;

    function KeyboardInput() {}

    _instance = void 0;

    KeyboardInput.get = function(args) {
      return _instance != null ? _instance : _instance = new _BlindKeyboardInput(args);
    };

    return KeyboardInput;

  })();

  _BlindKeyboardInput = (function() {

    function _BlindKeyboardInput(delegate) {
      this.handleKey = __bind(this.handleKey, this);

      var _this = this;
      this.delegate = delegate;
      this.rowCount = $("#grid tr").length;
      this.colCount = $("#grid tr:eq(1) td").length;
      this.modalKeyHandlers = [];
      $(window).keyup(function(e) {
        var _ref;
        if (_this.modalKeyHandlers.length !== 0) {
          return (_ref = _(_this.modalKeyHandlers).last()) != null ? _ref.handleKey(e) : void 0;
        } else {
          if (!isEditMode()) {
            return _this.handleKey(e);
          }
        }
      });
      this.setFocusPosition(0, 0);
    }

    _BlindKeyboardInput.prototype.pushModalKeyHandler = function(kh) {
      console.log("pushModalKeyHandler");
      this.modalKeyHandlers.push(kh);
      console.log("stopping timer **");
      return this.stopTimer();
    };

    _BlindKeyboardInput.prototype.popModalKeyHandler = function() {
      this.modalKeyHandlers.pop();
      if (this.modalKeyHandlers.length === 0 && !this.isInMenu()) {
        return this.startTimer();
      }
    };

    _BlindKeyboardInput.prototype.isInMenu = function(e) {
      return this.focusPosition().left === 0;
    };

    _BlindKeyboardInput.prototype.playNavigationSound = function() {
      this.stopNavigationSound();
      if ($(".keyboardFocus audio").attr('src') != null) {
        $(".keyboardFocus audio").each(function() {
          return this.play();
        });
        return true;
      }
      return false;
    };

    _BlindKeyboardInput.prototype.stopNavigationSound = function() {
      return $("#grid audio").each(function() {
        return this.pause();
      });
    };

    _BlindKeyboardInput.prototype.handleKey = function(e) {
      switch (String.fromCharCode(e.keyCode)) {
        case 'J':
          if (this.isInMenu()) {
            this.setFocusPosition(0, 0);
            this.playNavigationSound();
          } else {
            this.enter();
          }
          break;
        case 'N':
          if (this.isInMenu()) {
            this.setFocusPosition(0, 1);
            this.playNavigationSound();
          } else {
            this.pop(function() {
              return null;
            });
          }
          break;
        case 'M':
          if (this.isInMenu()) {
            this.setFocusPosition(1, 0);
            this.playNavigationSound();
            this.startTimer();
          } else {
            this.setFocusPosition(0, 0);
            this.stopTimer();
          }
          break;
        default:
          switch (e.keyCode) {
            case 37:
              this.splitStep(-1);
              break;
            case 39:
              this.splitStep(1);
              break;
            case 38:
              this.move(0, -1);
              break;
            case 40:
              this.move(0, 1);
              break;
            case 32:
              break;
            default:
              return true;
          }
      }
      return false;
    };

    _BlindKeyboardInput.prototype.getScannerDelay = function() {
      return parseInt($("#scannerDelay").val() || 1000);
    };

    _BlindKeyboardInput.prototype.startTimer = function() {
      var timerCallback,
        _this = this;
      this.stopTimer();
      timerCallback = function() {
        var played, startField, _results;
        _this.timeoutID = window.setTimeout(timerCallback, _this.getScannerDelay());
        console.log("set timeoutID to  " + _this.timeoutID);
        startField = $(".keyboardFocus")[0];
        played = false;
        _results = [];
        while (!played) {
          _this.splitStep(1);
          played = _this.playNavigationSound();
          if (startField === $(".keyboardFocus")[0]) {
            break;
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };
      this.timeoutID = window.setTimeout(timerCallback, this.getScannerDelay());
      return console.log("set timeoutID to  " + this.timeoutID);
    };

    _BlindKeyboardInput.prototype.stopTimer = function() {
      if (this.timeoutID != null) {
        console.log("STOP timer");
        window.clearTimeout(this.timeoutID);
        return this.timeoutID = null;
      } else {
        return console.log("not stopping, timeoutID is " + this.timeoutID);
      }
    };

    _BlindKeyboardInput.prototype.enter = function() {
      var focusPos,
        _this = this;
      this.stopTimer();
      this.stopNavigationSound();
      focusPos = this.focusPosition();
      if (focusPos != null) {
        return this.delegate.enterCell(focusPos.left, focusPos.top, function(err, result) {
          console.log("set focus pos to 1/0");
          if ((result != null) && ("content" in result)) {

          } else {
            _this.setFocusPosition(1, 0);
            _this.playNavigationSound();
            return _this.startTimer();
          }
        });
      }
    };

    _BlindKeyboardInput.prototype.pop = function(cb) {
      var _ref,
        _this = this;
      this.stopTimer();
      return (_ref = this.delegate) != null ? _ref.pop(function() {
        _this.setFocusPosition(1, 0);
        _this.playNavigationSound();
        _this.startTimer();
        return cb(null);
      }) : void 0;
    };

    _BlindKeyboardInput.prototype.focusPosition = function() {
      var cell, row, x, y;
      if ($(".keyboardFocus").length === 1) {
        cell = $(".keyboardFocus");
        row = cell.closest("tr");
        x = cell.index();
        y = row.index();
        return {
          left: x,
          top: y
        };
      } else {
        return {
          left: 0,
          top: 0
        };
      }
    };

    _BlindKeyboardInput.prototype.setFocusPosition = function(x, y) {
      $("#grid td").removeClass("keyboardFocus");
      return $("#grid tr").eq(y).find("td").eq(x).addClass("keyboardFocus");
    };

    _BlindKeyboardInput.prototype.move = function(dx, dy) {
      var cell, cells, focusPos, row, rows, x, y;
      if ($(".keyboardFocus").length === 0) {
        rows = $("#grid tr");
        row = rows.eq(Math.floor(rows.length / 2));
        cells = row.find("td");
        cell = cells.eq(Math.floor(cells.length / 2));
        return cell.addClass("keyboardFocus");
      } else {
        focusPos = this.focusPosition();
        x = focusPos.left;
        y = focusPos.top;
        x += dx;
        y += dy;
        if (x >= this.colCount) {
          x = 0;
        }
        if (x < 0) {
          x = this.colCount - 1;
        }
        if (y >= this.rowCount) {
          y = 0;
        }
        if (y < 0) {
          y = this.rowCount - 1;
        }
        return this.setFocusPosition(x, y);
      }
    };

    _BlindKeyboardInput.prototype.step = function(d, sx, sy, ex, ey) {
      var cell, cells, focusPos, row, rows, x, y;
      if (sx == null) {
        sx = 0;
      }
      if (sy == null) {
        sy = 0;
      }
      if (ex == null) {
        ex = this.colCount - 1;
      }
      if (ey == null) {
        ey = this.rowCount - 1;
      }
      if ($(".keyboardFocus").length === 0) {
        rows = $("#grid tr");
        row = rows.eq(sy);
        cells = row.find("td");
        cell = cells.eq(sx);
        return cell.addClass("keyboardFocus");
      } else {
        focusPos = this.focusPosition();
        x = focusPos.left;
        y = focusPos.top;
        x += d;
        if (x < sx) {
          x = ex;
          y--;
        }
        if (x > ex) {
          x = sx;
          y++;
        }
        if (y < sy) {
          y = ey;
          x = ex;
        }
        if (y > ey) {
          x = sx;
          y = sy;
        }
        return this.setFocusPosition(x, y);
      }
    };

    _BlindKeyboardInput.prototype.splitStep = function(d) {
      if (!this.isInMenu()) {
        return this.step(d, 1, 0, this.colCount - 1, this.rowCount - 1);
      } else {
        return this.step(d, 0, 0, 0, this.rowCount - 1);
      }
    };

    return _BlindKeyboardInput;

  })();

}).call(this);
