// Generated by CoffeeScript 1.3.3
(function() {
  var ImagePlayer;

  ImagePlayer = (function() {

    function ImagePlayer(dataURI) {
      var self;
      this.img = $(".imagePlayer img")[0];
      $(".imagePlayer .dialog").show();
      $(this.img).attr("src", dataURI);
      self = this;
      $(".imagePlayer .choice").click(function() {
        switch ($(this).attr("type")) {
          case "back":
            return self.close();
        }
      });
    }

    ImagePlayer.prototype.close = function() {
      return $(".imagePlayer .dialog").hide();
    };

    return ImagePlayer;

  })();

  window.ImagePlayer = ImagePlayer;

}).call(this);
