// Generated by CoffeeScript 1.3.3
(function() {
  var ImagePlayer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ImagePlayer = (function(_super) {

    __extends(ImagePlayer, _super);

    function ImagePlayer(dataURI, cb) {
      ImagePlayer.__super__.constructor.call(this, '.imagePlayer .dialog', cb);
      this.img = $('.imagePlayer img')[0];
      $(this.img).attr("src", dataURI);
    }

    return ImagePlayer;

  })(ModalDialog);

  window.ImagePlayer = ImagePlayer;

}).call(this);
