// Generated by CoffeeScript 1.3.3
(function() {
  var ImagePlayer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ImagePlayer = (function(_super) {

    __extends(ImagePlayer, _super);

    function ImagePlayer(dataURI) {
      var self;
      ImagePlayer.__super__.constructor.apply(this, arguments);
      this.img = $(".imagePlayer img")[0];
      $(".imagePlayer .dialog").show();
      $(this.img).attr("src", dataURI);
      self = this;
      $(".imagePlayer .choice").click(function() {
        switch ($(this).attr("type")) {
          case "back":
            return self.close();
        }
      });
    }

    ImagePlayer.prototype.close = function() {
      ImagePlayer.__super__.close.apply(this, arguments);
      return $(".imagePlayer .dialog").hide();
    };

    return ImagePlayer;

  })(ModalDialog);

  window.ImagePlayer = ImagePlayer;

}).call(this);
