// Generated by CoffeeScript 1.3.3
(function() {
  var ModalDialog,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ModalDialog = (function() {

    function ModalDialog() {
      this.handleKey = __bind(this.handleKey, this);
      KeyboardInput.get().pushModalKeyHandler(this);
    }

    ModalDialog.prototype.close = function() {
      return KeyboardInput.get().popModalKeyHandler();
    };

    ModalDialog.prototype.handleKey = function(e) {
      switch (String.fromCharCode(e.keyCode)) {
        case 'J':
          return this.leftKeyPressed();
        case 'N':
          return this.rightKeyPressed();
        case 'M':
          return this.middleKeyPressed();
      }
    };

    ModalDialog.prototype.leftKeyPressed = function() {};

    ModalDialog.prototype.rightKeyPressed = function() {
      return this.close();
    };

    ModalDialog.prototype.middleKeyPressed = function() {};

    return ModalDialog;

  })();

  window.ModalDialog = ModalDialog;

}).call(this);
