// Generated by CoffeeScript 1.3.3
(function() {
  var NavigationController;

  NavigationController = (function() {

    function NavigationController(grid) {
      this.grid = grid;
      this.controllerStack = [];
    }

    NavigationController.prototype.push = function(newSource) {
      this.controllerStack.push(newSource);
      return this.grid.reloadFromDataSource(newSource);
    };

    NavigationController.prototype.pop = function() {
      var lastController;
      this.controllerStack.pop();
      lastController = _(this.controllerStack).last();
      return this.grid.reloadFromDataSource(lastController);
    };

    NavigationController.prototype.popToRoot = function() {
      var _results;
      _results = [];
      while (this.controllerStack.length > 1) {
        _results.push(this.pop());
      }
      return _results;
    };

    NavigationController.prototype.count = function() {
      return this.controllerStack.length;
    };

    NavigationController.prototype.currentController = function() {
      return _(this.controllerStack).last();
    };

    return NavigationController;

  })();

  window.NavigationController = NavigationController;

}).call(this);
