// Generated by CoffeeScript 1.3.3
(function() {
  var NavigationController;

  NavigationController = (function() {

    function NavigationController(grid) {
      this.grid = grid;
      this.controllerStack = [];
    }

    NavigationController.prototype.push = function(newSource, cb) {
      this.controllerStack.push(newSource);
      return this.grid.reloadFromDataSource(newSource, cb);
    };

    NavigationController.prototype.pop = function(cb) {
      var lastController;
      this.controllerStack.pop();
      lastController = _(this.controllerStack).last();
      return this.grid.reloadFromDataSource(lastController, cb);
    };

    NavigationController.prototype.popToRoot = function(cb) {
      var _this = this;
      if (this.controllerStack.length > 1) {
        return this.pop(function() {
          return _this.popToRoot(cb);
        });
      } else {
        return cb(null);
      }
    };

    NavigationController.prototype.count = function() {
      return this.controllerStack.length;
    };

    NavigationController.prototype.currentController = function() {
      return _(this.controllerStack).last();
    };

    return NavigationController;

  })();

  window.NavigationController = NavigationController;

}).call(this);
