// Generated by CoffeeScript 1.3.3
(function() {
  var SplitDataSource;

  SplitDataSource = (function() {

    function SplitDataSource(ds1, ds2, splitColumn) {
      this.ds1 = ds1;
      this.ds2 = ds2;
      this.splitColumn = splitColumn;
    }

    SplitDataSource.prototype.enterCell = function(x, y, cb) {
      return (x < this.splitColumn ? this.ds1 : this.ds2).enterCell(x, y, cb);
    };

    SplitDataSource.prototype.cellForPosition = function(x, y, cb) {
      return (x < this.splitColumn ? this.ds1 : this.ds2).cellForPosition(x, y, cb);
    };

    return SplitDataSource;

  })();

  window.SplitDataSource = SplitDataSource;

}).call(this);
