// Generated by CoffeeScript 1.3.3
(function() {
  var Talkshow;

  Talkshow = (function() {

    function Talkshow() {
      var grid, keyboardInput, myDataSource, rootNodeId, splitDataSource;
      grid = new Grid(4, 2);
      this.navigationController = new NavigationController(grid);
      rootNodeId = localStorage.getItem("root");
      console.log("rootNodeId", rootNodeId);
      myDataSource = new DataSource(grid, 1, rootNodeId);
      myDataSource.delegate = this;
      this.yesNoDataSource = new DataSource(grid, 1, "yes_no");
      splitDataSource = new SplitDataSource(this.yesNoDataSource, myDataSource, 1);
      this.navigationController.push(splitDataSource);
      keyboardInput = KeyboardInput.get(this);
    }

    Talkshow.prototype.enterCell = function(x, y) {
      return this.navigationController.currentController().enterCell(x, y);
    };

    Talkshow.prototype.pop = function() {
      if (this.navigationController.count() > 1) {
        return this.navigationController.pop();
      }
    };

    Talkshow.prototype.enteredCell = function(dataSource, position, level, nodeId) {
      var myDataSource, splitDataSource;
      console.log("enteredCell " + position.x + "/" + position.y + " level: " + level + " nodeId: " + nodeId);
      myDataSource = new DataSource(this.grid, level, nodeId, dataSource, position);
      myDataSource.delegate = this;
      splitDataSource = new SplitDataSource(this.yesNoDataSource, myDataSource, 1);
      return this.navigationController.push(splitDataSource);
    };

    return Talkshow;

  })();

  window.Talkshow = Talkshow;

}).call(this);
